services:
  app:
    build: .
    container_name: prediccion_agro
    ports:
      - "8050:8050"   
    volumes:
      - .:/app        
    environment:
      - PYTHONUNBUFFERED=1
    command: python src/app.py